config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'panels#index'

  get 'esqueceu_sua_senha', to: 'panels#forgot_your_password'
  post 'check_credentials', to: 'panels#check_credentials'
  post 'send_password',     to: 'panels#send_password'
  patch 'update_password',  to: 'panels#update_password'

  get 'cliente/esqueceu_sua_senha', to: 'customer_panel#forgot_your_password'

  get 'gestao/esqueceu_sua_senha', to: 'employee_panel#forgot_your_password'

  get 'cliente/dashboard/trocar_senha', to: 'customer_panel#change_password'

  get 'gestao/dashboard/trocar_senha', to: 'employee_panel#change_password'

  scope module: 'customer_panel', path: 'cliente', as: 'customer_panel' do
    get 'main'
    get 'login'
    get 'logout'
    get 'states'
    get 'cities'

    get 'dashboard/index'
    get 'dashboard/escolta/nao_finalizadas',             to: 'escort#not_finished'
    get 'dashboard/escolta/finalizadas',                 to: 'escort#finished'
    get 'dashboard/escolta/novo',                        to: 'escort#new'
    get 'dashboard/escolta/:order_number',               to: 'escort#show',      as: 'escort_show'
    get 'dashboard/escolta/pre_alert/:order_number',     to: 'escort#pre_alert', as: 'escort_pre_alert'
    get 'dashboard/escolta/service_order/:order_number', to: 'escort#service_order', as: 'escort_service_order'
    post 'dashboard/escolta/create',                     to: 'escort#create'
    delete 'dashboard/escolta/cancel/:order_number',     to: 'escort#cancel',    as: 'escort_cancel'
  end

  scope module: 'employee_panel', path: 'gestao', as: 'employee_panel' do
    get 'login'
    get 'logout'
    get 'dashboard/index'

    scope module: 'administrator_panel', path: 'admin', as: 'administrator' do
      get 'dashboard/index'

      get 'dashboard/escoltas/:status',                to: 'dashboard/escorts#escorts', as: 'dashboard_escorts'
      get 'dashboard/escolta/:order_number',           to: 'dashboard/escorts#show',    as: 'dashboard_escort_show'
      patch 'dashboard/escolta/unblock/:order_number', to: 'dashboard/escorts#unblock', as: 'dashboard_escort_unblock'

      get 'dashboard/clientes',              to: 'dashboard/customers#list'
      get 'dashboard/cliente/novo',          to: 'dashboard/customers#new'
      get 'dashboard/cliente/:id',           to: 'dashboard/customers#show',   as: 'dashboard_customer_show'
      get 'dashboard/cliente/:id/editar',    to: 'dashboard/customers#edit',   as: 'dashboard_customer_edit'
      post 'dashboard/cliente/create',       to: 'dashboard/customers#create'
      patch 'dashboard/cliente/update/:id',  to: 'dashboard/customers#update', as: 'dashboard_customer_update'
      delete 'dashboard/cliente/remove/:id', to: 'dashboard/customers#remove', as: 'dashboard_customer_remove'

      get 'dashboard/funcionarios',              to: 'dashboard/employees#list'
      get 'dashboard/funcionario/novo',          to: 'dashboard/employees#new'
      get 'dashboard/funcionario/:id',           to: 'dashboard/employees#show',   as: 'dashboard_employee_show'
      get 'dashboard/funcionario/:id/editar',    to: 'dashboard/employees#edit',   as: 'dashboard_employee_edit'
      post 'dashboard/funcionario/create',       to: 'dashboard/employees#create'
      patch 'dashboard/funcionario/update/:id',  to: 'dashboard/employees#update', as: 'dashboard_employee_update'
      delete 'dashboard/funcionario/remove/:id', to: 'dashboard/employees#remove', as: 'dashboard_employee_remove'

      get 'dashboard/equipamentos',              to: 'dashboard/tackles#list'
      get 'dashboard/equipamento/novo',          to: 'dashboard/tackles#new'
      get 'dashboard/equipamento/:id',           to: 'dashboard/tackles#show',   as: 'dashboard_tackle_show'
      get 'dashboard/equipamento/:id/editar',    to: 'dashboard/tackles#edit',   as: 'dashboard_tackle_edit'
      post 'dashboard/equipamento/create',       to: 'dashboard/tackles#create'
      patch 'dashboard/equipamento/update/:id',  to: 'dashboard/tackles#update', as: 'dashboard_tackle_update'
      delete 'dashboard/equipamento/remove/:id', to: 'dashboard/tackles#remove', as: 'dashboard_tackle_remove'

      get 'dashboard/arsenais/armas',              to: 'dashboard/arsenals/guns#list'
      get 'dashboard/arsenais/arma/novo',          to: 'dashboard/arsenals/guns#new'
      get 'dashboard/arsenais/arma/:id',           to: 'dashboard/arsenals/guns#show',   as: 'dashboard_gun_show'
      get 'dashboard/arsenais/arma/:id/editar',    to: 'dashboard/arsenals/guns#edit',   as: 'dashboard_gun_edit'
      post 'dashboard/arsenais/arma/create',       to: 'dashboard/arsenals/guns#create'
      delete 'dashboard/arsenais/arma/remove/:id', to: 'dashboard/arsenals/guns#remove', as: 'dashboard_gun_remove'
      patch 'dashboard/arsenais/arma/update/:id',  to: 'dashboard/arsenals/guns#update', as: 'dashboard_gun_update'

      get 'dashboard/arsenais/municao/novo',          to: 'dashboard/arsenals/munitions#new'
      get 'dashboard/arsenais/municoes',              to: 'dashboard/arsenals/munitions#list'
      get 'dashboard/arsenais/municao/:id/editar',    to: 'dashboard/arsenals/munitions#edit',   as: 'dashboard_munition_edit'
      post 'dashboard/arsenais/municao/create',       to: 'dashboard/arsenals/munitions#create'
      patch 'dashboard/arsenais/municao/update/:id',  to: 'dashboard/arsenals/munitions#update', as: 'dashboard_munition_update'
      delete 'dashboard/arsenais/municao/remove/:id', to: 'dashboard/arsenals/munitions#remove', as: 'dashboard_munition_remove'

      get 'dashboard/viatura/novo',          to: 'dashboard/vehicles#new'
      get 'dashboard/viaturas',              to: 'dashboard/vehicles#list'
      get 'dashboard/viatura/:id',           to: 'dashboard/vehicles#show',   as: 'dashboard_vehicle_show'
      get 'dashboard/viatura/:id/editar',    to: 'dashboard/vehicles#edit',   as: 'dashboard_vehicle_edit'
      post 'dashboard/viatura/create',       to: 'dashboard/vehicles#create'
      patch 'dashboard/viatura/update/:id',  to: 'dashboard/vehicles#update', as: 'dashboard_vehicle_update'
      delete 'dashboard/viatura/remove/:id', to: 'dashboard/vehicles#remove', as: 'dashboard_vehicle_remove'

      get 'dashboard/relatorios/escoltas',     to: 'dashboard/reports#escorts'
      get 'dashboard/relatorios/clientes',     to: 'dashboard/reports#customers'
      get 'dashboard/relatorios/armas',        to: 'dashboard/reports#guns'
      get 'dashboard/relatorios/municoes',     to: 'dashboard/reports#munitions'
      get 'dashboard/relatorios/equipamentos', to: 'dashboard/reports#tackles'
      get 'dashboard/relatorios/funcionarios', to: 'dashboard/reports#employees'
      get 'dashboard/relatorios/viaturas',     to: 'dashboard/reports#vehicles'

      get 'dashboard/graficos/escorts_by_status', to: 'dashboard/graphics#escorts_by_status'
    end

    scope module: 'agent_panel', path: 'agente', as: 'agent' do
      get 'dashboard'
    end

    scope module: 'lecturer_panel', path: 'conferente', as: 'lecturer' do
      get 'dashboard'
    end

    scope module: 'operator_panel', path: 'operador', as: 'operator' do
      get 'dashboard/index'

      get 'dashboard/gerenciamento/:order_number',     to: 'orders#order_management', as:  'dashboard_order_management'
      post 'dashboard/gerenciamento/mount_items_list', to: 'missions#mount_items_list'
      post 'dashboard/gerenciamento/mount_team',       to: 'teams#mount_team'
      post 'dashboard/gerenciamento/refuse_team',      to: 'teams#refuse_team'
      post 'dashboard/gerenciamento/block_order',      to: 'orders#block_order'
      post 'dashboard/gerenciamento/confirm_order',    to: 'orders#confirm_order'
      post 'dashboard/gerenciamento/refuse_order',     to: 'orders#refuse_order'

      get 'dashboard/missoes',                  to: 'missions#missions'
      get 'dashboard/missao/:order_number',     to: 'missions#mission', as: 'dashboard_mission'
      post 'dashboard/missao/start_mission',    to: 'missions#start_mission'
      post 'dashboard/missao/finish_mission',   to: 'missions#finish_mission'
      patch 'dashboard/missao/start_mission',   to: 'missions#start_mission'
      patch 'dashboard/missao/exit_from_base',  to: 'missions#exit_from_base'
      patch 'dashboard/missao/arrival_at_base', to: 'missions#arrival_at_base'
    end
  end
end

app/controllers/customer_panel/dashboard_controller.rb
# frozen_string_literal: true

# frozen_string_litral: true

module CustomerPanel
  class DashboardController < PanelsController
    def index; end
  end
end

app/controllers/employee_panel/administrator_panel/dashboard/arsenals/guns_controller.rb
# frozen_string_literal: true

module EmployeePanel
  module AdministratorPanel
    module Dashboard
      module Arsenals
        class GunsController < ArsenalsController
          before_action { check_internal_profile(params['controller']) }

          def list
            @guns = Gun.all
          end

          def new; end

          def edit
            @gun = Gun.find(params['id'])
          rescue StandardError, ActiveRecord::RecordNotFound => error
            redirect_to employee_panel_administrator_dashboard_arsenais_armas_path,
                        alert: error_message(error.class, :find)
          end

          def create
            gun = Gun.new(gun_params)

            gun.validate
            gun.save!

            redirect_to employee_panel_administrator_dashboard_arsenais_armas_path,
                        notice: t('messages.successes.arsenal.gun.created_successfully',
                                  sinarm: gun.sinarm)
          rescue StandardError => error
            Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

            redirect_to employee_panel_administrator_dashboard_arsenais_arma_novo_path,
                        alert: t('messages.errors.arsenal.gun.create_failed')
          end

          def show
            @gun = Gun.find(params['id'])
          rescue StandardError, ActiveRecord::RecordNotFound => error
            redirect_to employee_panel_administrator_dashboard_arsenais_armas_path,
                        alert: error_message(error.class, :find)
          end

          def update
            gun = Gun.find(params['id'])

            gun.update!(gun_params)

            redirect_to employee_panel_administrator_dashboard_gun_show_path(gun.id),
                        notice: t('messages.successes.arsenal.gun.updated_successfully')
          rescue StandardError, ActiveRecord::RecordNotFound => error
            redirect_to employee_panel_administrator_dashboard_arsenais_armas_path,
                        alert: error_message(error.class, :update)
          end

          def remove
            delete_gun!

            redirect_to employee_panel_administrator_dashboard_arsenais_armas_path,
                        notice: t('messages.successes.arsenal.gun.removed_successfully',
                                  sinarm: gun.sinarm)
          rescue DeleteGunError
            redirect_to employee_panel_administrator_dashboard_arsenais_armas_path,
                        alert: t('messages.errors.arsenal.gun.remove_in_mission_failed')
          rescue StandardError, ActiveRecord::RecordNotFound => error
            redirect_to employee_panel_administrator_dashboard_arsenais_armas_path,
                        alert: error_message(error.class, :remove)
          end

          private

          def delete_gun!
            raise DeleteGunError if gun.in_mission?

            gun.delete
          end

          def gun
            @gun ||= Gun.find(params['id'])
          end

          def error_message(error_class, action)
            if error_class == ActiveRecord::RecordNotFound
              t('messages.errors.arsenal.gun.not_found')
            else
              t("messages.errors.#{action}_failed")
            end
          end

          def status_params!(formatted_params)
            if params['gun']['status']
              formatted_params.merge!('status' => Status.find_by_name(params['gun']['status']))
            else
              formatted_params
            end
          end

          def gun_params
            formatted_params = params
                               .require(:gun)
                               .permit(:kind, :caliber, :number, :sinarm, :registration_validity,
                                       :linked_at_post, :situation)

            status_params!(formatted_params)
          end
        end
      end
    end
  end
end

app/controllers/employee_panel/administrator_panel/dashboard/arsenals/munitions_controller.rb
# frozen_string_literal: true

module EmployeePanel
  module AdministratorPanel
    module Dashboard
      module Arsenals
        class MunitionsController < ArsenalsController
          before_action { check_internal_profile(params['controller']) }

          def list
            @munitions = MunitionStock.all
          end

          def new; end

          def edit
            @munition = MunitionStock.find(params['id'])
          rescue StandardError, ActiveRecord::RecordNotFound => error
            redirect_to employee_panel_administrator_dashboard_arsenais_municoes_path,
                        alert: error_message(error.class, :find)
          end

          def create
            munition = MunitionStock.new(munition_params)

            munition.validate
            munition.save!

            redirect_to employee_panel_administrator_dashboard_arsenais_municoes_path,
                        notice: t('messages.successes.arsenal.munition.created_successfully',
                                  caliber_type: munition.caliber)
          rescue StandardError => error
            Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

            redirect_to employee_panel_administrator_dashboard_arsenais_municao_novo_path,
                        alert: t('messages.errors.arsenal.munition.create_failed')
          end

          def update
            munition = MunitionStock.find(params['id'])

            munition.update!(munition_params)

            redirect_to employee_panel_administrator_dashboard_arsenais_municoes_path,
                        notice: t('messages.successes.arsenal.munition.updated_successfully')
          rescue StandardError, ActiveRecord::RecordNotFound => error
            redirect_to employee_panel_administrator_dashboard_arsenais_municoes_path,
                        alert: error_message(error.class, :update)
          end

          def remove
            munition.delete

            redirect_to employee_panel_administrator_dashboard_arsenais_municoes_path,
                        notice: t('messages.successes.arsenal.munition.removed_successfully',
                                  caliber_type: munition.caliber)
          rescue StandardError, ActiveRecord::RecordNotFound => error
            redirect_to employee_panel_administrator_dashboard_arsenais_municoes_path,
                        alert: error_message(error.class, :remove)
          end

          private

          def munition
            @munition ||= MunitionStock.find(params['id'])
          end

          def error_message(error_class, action)
            if error_class == ActiveRecord::RecordNotFound
              t('messages.errors.arsenal.munition.not_found')
            else
              t("messages.errors.#{action}_failed")
            end
          end

          def munition_params
            params
              .require(:munition)
              .permit(:caliber, :quantity)
              .merge!({ 'last_update' => DateTime.now })
          end
        end
      end
    end
  end
end

app/controllers/employee_panel/administrator_panel/dashboard/arsenals_controller.rb
# frozen_string_literal: true

module EmployeePanel
  module AdministratorPanel
    module Dashboard
      class ArsenalsController < EmployeePanelController
        before_action { check_internal_profile(params['controller']) }
      end
    end
  end
end

app/controllers/employee_panel/administrator_panel/dashboard/graphics_controller.rb
# frozen_string_literal: true

module EmployeePanel
  module AdministratorPanel
    module Dashboard
      class GraphicsController < EmployeePanelController
        before_action { check_internal_profile(params['controller']) }

        def escorts_by_status
          chart_data = Order.chart_by_status

          render json: { 'chart_data' => chart_data }, status: :ok
        rescue StandardError => error
          Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

          render json: { 'chart_data' => [] }, status: :internal_server_error
        end
      end
    end
  end
end

app/controllers/employee_panel/administrator_panel/dashboard_controller.rb
# frozen_string_literal: true

module EmployeePanel
  module AdministratorPanel
    class DashboardController < EmployeePanelController
      before_action { check_internal_profile(params['controller']) }

      def index; end
    end
  end
end

app/controllers/employee_panel/dashboard_controller.rb
# frozen_string_literal: true

module EmployeePanel
  class DashboardController < PanelsController
    before_action :router, only: [:index]

    def index; end

    private

    def router
      redirect_to send("employee_panel_#{profile}_dashboard_index_path")
    rescue StandardError => error
      Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

      redirect_to employee_panel_login_path
    end

    def profile
      @profile ||= session[:employee_profile].downcase
    end
  end
end

app/views/employee_panel/operator_panel/dashboard/index.html.erb
<h1 class="mt-4"><%= t('.title') %></h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item active"><%= t('breadcrumbs.escort_requests') %></li>
</ol>
<%= render './partials/messages' %>
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    <%= t('.requests_list') %>
  </div>
  <div class="card-body">
    <table id="tableOperatorEscort" class="table table-striped" width="100%">
      <thead>
        <tr>
          <th><%= t('.order') %></th>
          <th><%= t('.customer_name') %></th>
          <th><%= t('.job_date_time') %></th>
          <th><%= t('.source') %></th>
          <th><%= t('.destiny') %></th>
          <th><%= t('.observation') %></th>
          <th></th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th><%= t('.order') %></th>
          <th><%= t('.customer_name') %></th>
          <th><%= t('.job_date_time') %></th>
          <th><%= t('.source') %></th>
          <th><%= t('.destiny') %></th>
          <th><%= t('.observation') %></th>
          <th></th>
        </tr>
      </tfoot>
      <tbody>
        <% @scheduled_escorts.each do |escort| %>
          <tr>
            <td><%= escort.order_number %></td>
            <td><%= escort.customer.company %></td>
            <td><%= convert_date_time(escort.prevision) %></td>
            <td><%= escort.source_state %></td>
            <td><%= escort.destiny_state %></td>
            <td><%= escort.observation %></td>
            <td>
              <%= link_to employee_panel_operator_dashboard_order_management_path(escort.order_number) do %>
                <i class="fas fa-calendar-check me-1"></i></td>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @scheduled_escorts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/employee_panel/operator_panel/dashboard/mission.html.erb
<h1 class="mt-4"><%= t('.title') %></h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">
    <%= link_to t('breadcrumbs.escort_missions'), employee_panel_operator_dashboard_missoes_path %>
  </li>
  <li class="breadcrumb-item active"><%= t('breadcrumbs.mission_number', mission_number: @mission.id) %></li>
</ol>
<hr>
<div id="layoutOrderManagementt">
  <div id="layoutOrderManagementt_content">
    <main>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12">
            <br>
            <%= render './partials/messages' %>
            <div class="card shadow-lg border-0 rounded-lg mt-5">
              <div class="card-body">

                <!-- MISSION STATUS -->
                <h5><%= t('.status') %></h5>
                <h6><strong><%= @mission.status.name.upcase %></strong></h6>

                <hr>

                <!-- CUSTOMER DATA -->
                <h5><%= t('.way') %></h5>
                <h6><%= t('.source') %></h6>
                <strong><%= t('.job_day') %></strong>
                <span><%= @mission.escort_service.job_day %></span>
                <br>
                <strong><%= t('.job_horary') %></strong>
                <span><%= @mission.escort_service.job_horary %></span>
                <br>
                <strong><%= t('.address') %></strong>
                <span><%= @mission.escort_service.source_address %></span>
                <br>
                <strong><%= t('.number') %></strong>
                <span><%= @mission.escort_service.source_number %></span>
                <br>
                <strong><%= t('.complement') %></strong>
                <span><%= @mission.escort_service.source_complement %></span>
                <br>
                <strong><%= t('.district') %></strong>
                <span><%= @mission.escort_service.source_district %></span>
                <br>
                <strong><%= t('.city') %></strong>
                <span><%= @mission.escort_service.source_city %></span>
                <br>
                <strong><%= t('.state') %></strong>
                <span><%= @mission.escort_service.source_state %></span>
                <br><br>
                <h6><%= t('.destiny') %></h6>
                <strong><%= t('.address') %></strong>
                <span><%= @mission.escort_service.destiny_address %></span>
                <br>
                <strong><%= t('.number') %></strong>
                <span><%= @mission.escort_service.destiny_number %></span>
                <br>
                <strong><%= t('.complement') %></strong>
                <span><%= @mission.escort_service.destiny_complement %></span>
                <br>
                <strong><%= t('.district') %></strong>
                <span><%= @mission.escort_service.destiny_district %></span>
                <br>
                <strong><%= t('.city') %></strong>
                <span><%= @mission.escort_service.destiny_city %></span>
                <br>
                <strong><%= t('.state') %></strong>
                <span><%= @mission.escort_service.destiny_state %></span>
                <br><br>
                <strong><%= t('.observation') %></strong>
                <span><%= @mission.escort_service.observation %></span>
                <br>

                <hr>

                <!-- TEAM DATA-->
                <h5><%= t('.team') %></h5>
                <strong><%= t('.team_name') %></strong>
                <span><%= @mission.team.name %></span>
                <br>
                <strong><%= t('.agents', count: @mission.team.agents.count) %></strong>
                <span><%= mission_fullnames_with_document(@mission) %><span>
                <br>

                <hr>

                <!-- GUNS DATA-->
                <h5><%= t('.arsenal') %></h5>
                <strong><%= t('.guns') %></strong>
                <span><%= mission_guns(@mission) %></span>
                <br>

                <hr>

                <!-- MUNITIONS DATA-->
                <h5><%= t('.munitions') %></h5>
                <strong><%= t('.description') %></strong>
                <span><%= mission_munitions(@mission) %></span>
                <br>

                <hr>

                <!-- TACKLES DATA-->
                <h5><%= t('.tackles') %></h5>
                <strong><%= t('.waistcoats') %></strong>
                <span><%= mission_waistcoats(@mission) %></span>
                <br>
                <strong><%= t('.radios') %></strong>
                <span><%= mission_radios(@mission) %></span>
                <br>

                <hr>

                <!-- VEHICLES DATA-->
                <h5><%= t('.vehicles') %></h5>
                <strong><%= t('.description') %></strong>
                <span><%= mission_vehicles(@mission) %></span>
                <br>

                <hr>
                <% if @mission.exit_from_base.nil? && @mission.arrival_at_base.nil? && @mission.started_at.nil? && @mission.finished_at.nil? %>
                  <%= link_to t('.exit_from_base_btn'),
                              employee_panel_operator_dashboard_missao_exit_from_base_path(order_number: @mission.escort_service.order_number),
                              method: :patch,
                              class: 'btn btn-primary' %>
                <% end %>
                <% if @mission.exit_from_base.present? && @mission.arrival_at_base.nil? && @mission.started_at.nil? && @mission.finished_at.nil?%>
                  <%= link_to t('.start_mission_btn'),
                                employee_panel_operator_dashboard_missao_start_mission_path(order_number: @mission.escort_service.order_number),
                                method: :patch,
                                class: 'btn btn-success' %>
                <% end %>
                <% if @mission.exit_from_base.present? && @mission.arrival_at_base.nil? && @mission.started_at.present? && @mission.finished_at.nil? %>
                  <button class="btn btn-danger" id="finishMissionObservationModalBtn">
                    <%= t('.finish_mission_btn') %>
                  </button>

                  <%= render './partials/finish_mission_observation_modal' %>
                <% end %>
                <% if @mission.exit_from_base.present? && @mission.arrival_at_base.nil? && @mission.started_at.present? && @mission.finished_at.present? %>
                  <%= link_to t('.arrival_at_base_btn'),
                              employee_panel_operator_dashboard_missao_arrival_at_base_path(order_number: @mission.escort_service.order_number),
                              method: :patch,
                              class: 'btn btn-primary' %>
                <% end %>
              </div>
              <div class="card-footer text-center py-3"></div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

app/views/employee_panel/operator_panel/dashboard/missions.html.erb
<h1 class="mt-4"><%= t('.title') %></h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item active"><%= t('breadcrumbs.escort_missions') %></li>
</ol>
<%= render './partials/messages' %>
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    <%= t('.missions_list') %>
  </div>
  <div class="card-body">
    <table id="tableOperatorEscort" class="table table-striped" width="100%">
      <thead>
        <tr>
          <th><%= t('.order') %></th>
          <th><%= t('.team') %></th>
          <th><%= t('.exit_from_base') %></th>
          <th><%= t('.started_at') %></th>
          <th><%= t('.finished_at') %></th>
          <th><%= t('.arrival_at_base') %>
          <th><%= t('.status') %></th>
          <th></th>
        </tr>
      </thead>
      <% if @missions.any? %>
        <tfoot>
          <tr>
            <th><%= t('.order') %></th>
            <th><%= t('.team') %></th>
            <th><%= t('.exit_from_base') %></th>
            <th><%= t('.started_at') %></th>
            <th><%= t('.finished_at') %></th>
            <th><%= t('.arrival_at_base') %>
            <th><%= t('.status') %></th>
            <th></th>
          </tr>
        </tfoot>
      <% end %>
      <tbody>
        <% @missions.each do |mission| %>
          <tr>
            <td><%= mission.escort_service.order_number %></td>
            <td><%= mission.team.name %></td>
            <td><%= convert_date_time(mission.exit_from_base) if mission.exit_from_base %></td>
            <td><%= convert_date_time(mission.started_at) if mission.started_at %></td>
            <td><%= convert_date_time(mission.finished_at) if mission.finished_at %></td>
            <td><%= convert_date_time(mission.arrival_at_base) if mission.arrival_at_base %></td>
            <td><%= mission.status.name %></td>
            <td>
              <%= link_to employee_panel_operator_dashboard_mission_path(mission.escort_service.order_number), title: t('.details') do %>
                <i class="fas fa-align-justify me-1"></i></td>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @missions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>